spring.application.name=bibliotheque-universitaire
server.port=8081 
server.servlet.context-path=/api


# DATABASE CONFIGURATION (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:bibliotheque
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (Interface web)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ===============================
# JPA/HIBERNATE CONFIGURATION
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# Activation de l'initialisation SQL
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
# ===============================
# SOAP WEB SERVICES CONFIGURATION
# ===============================
spring.webservices.path=/ws
spring.webservices.wsdl-locations=classpath:/wsdl/bibliotheque.wsdl

# ===============================
# LOGGING CONFIGURATION
# ===============================
logging.level.org.springframework.web=INFO
logging.level.com.bibliotheque=DEBUG